name: ESP32C3 Test Execution

on:
  push:
  workflow_dispatch:

jobs:
  esp32c3-execution:
    runs-on:
      - self-hosted
      - cirunner-type-vm
      - cirunner-size-micro
      - cirunner-image-ubuntu-runner-vm
      - cirunner-hardware-esp32c3

    steps:
      - name: install usb utils
        run: apt update && apt install usbutils

      - name: run uhubctl
        run: uhubctl

      - name: lsusb
        run: lsusb